// Copyright 2013 Eric Raijmakers.
//
// This file is part of Vidiot.
//
// Vidiot is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Vidiot is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Vidiot. If not, see <http://www.gnu.org/licenses/>.

#ifndef UTIL_EVENT_H
#define UTIL_EVENT_H

/// Implemented with a macro instead of a template, since I wasn't able
/// to use the event enum. It isn't const at compile time,
/// since it's generated by wxNewEventType().
///
/// In case of
/// warning C4717: 'gui::operator<<' : recursive on all control paths, function will cause runtime stack overflow
/// ensure that
/// std::ostream& operator<<( std::ostream& os, const objecttype& obj )
/// is defined.

#define DECLARE_EVENT(enumname, classname, objecttype)                                  \
    class classname : public wxEvent                                                    \
    {                                                                                   \
    public:                                                                             \
        classname(objecttype value);                                                    \
        classname(const classname& other);                                              \
        virtual wxEvent* Clone() const;                                                 \
        objecttype getValue() const;                                                    \
    private:                                                                            \
        friend std::ostream& operator<<( std::ostream& os, const classname& obj );      \
        objecttype mValue;                                                              \
    };                                                                                  \
    wxDECLARE_EVENT(enumname, classname);

#define DEFINE_EVENT(enumname, classname, objecttype)                                   \
    classname::classname(objecttype value)                                              \
    :   wxEvent(wxID_ANY, enumname)                                                     \
    ,   mValue(value)                                                                   \
    {}                                                                                  \
    classname::classname(const classname& other)                                        \
    :   wxEvent(other)                                                                  \
    ,   mValue(other.mValue)                                                            \
    {}                                                                                  \
    wxEvent* classname::Clone() const                                                   \
    {                                                                                   \
        return new classname(*this);                                                    \
    }                                                                                   \
    objecttype classname::getValue() const                                              \
    {                                                                                   \
        return mValue;                                                                  \
    }                                                                                   \
    std::ostream& operator<<( std::ostream& os, const classname& obj )                  \
    {                                                                                   \
        os << &obj << '|' << obj.getValue();                                            \
        return os;                                                                      \
    }                                                                                   \
    wxDEFINE_EVENT(enumname, classname);

#endif // UTIL_EVENT_H