#ifndef PRECOMPILED_H
#define PRECOMPILED_H

#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <boost/assert.hpp>
#include <boost/assign/list_of.hpp>
#include <boost/bimap.hpp>
#include <boost/bind.hpp>
#include <boost/config.hpp>
#include <boost/enable_shared_from_this.hpp>
#include <boost/foreach.hpp>
#include <boost/function.hpp>
#include <boost/make_shared.hpp>
#include <boost/mpl/list.hpp>
#include <boost/noncopyable.hpp>
#include <boost/optional.hpp>
#include <boost/statechart/custom_reaction.hpp>
#include <boost/statechart/state.hpp>
#include <boost/statechart/state_machine.hpp>
#include <boost/thread.hpp>
#include <boost/thread/barrier.hpp>
#include <list>
#include <map>
#include <math.h>
#include <ostream>
#include <set>
#include <vector>
#include <wx/artprov.h>
#include <wx/bitmap.h>
#include <wx/bookctrl.h>
#include <wx/button.h>
#include <wx/choice.h>
#include <wx/collpane.h>
#include <wx/config.h>
#include <wx/datetime.h>
#include <wx/dc.h>
#include <wx/dcclient.h>
#include <wx/dcgraph.h>
#include <wx/dcmemory.h>
#include <wx/debugrpt.h>
#include <wx/dir.h>
#include <wx/dirdlg.h>
#include <wx/dnd.h>
#include <wx/dnd.h>
#include <wx/event.h>
#include <wx/filedlg.h>
#include <wx/filename.h>
#include <wx/gauge.h>
#include <wx/gbsizer.h>
#include <wx/gdicmn.h>
#include <wx/graphics.h>
#include <wx/listbook.h>
#include <wx/msgdlg.h>
#include <wx/panel.h>
#include <wx/pen.h>
#include <wx/propgrid/propgrid.h>
#include <wx/radiobox.h>
#include <wx/sizer.h>
#include <wx/spinctrl.h>
#include <wx/statbox.h>
#include <wx/stattext.h>
#include <wx/string.h>
#include <wx/textctrl.h>
#include <wx/textdlg.h>
#include <wx/thread.h>
#include <wx/tokenzr.h>
#include <wx/tooltip.h>
#include <wx/window.h>

#include "Pointers.h"

#endif // PRECOMPILED_H